# Generated by Django 3.2.4 on 2021-08-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20210819_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
